/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as VideoNRouteImport } from './routes/video.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoNRoute = VideoNRouteImport.update({
  id: '/video/$n',
  path: '/video/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/intro': typeof IntroRoute
  '/portal': typeof PortalRoute
  '/video/$n': typeof VideoNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/intro': typeof IntroRoute
  '/portal': typeof PortalRoute
  '/video/$n': typeof VideoNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/intro': typeof IntroRoute
  '/portal': typeof PortalRoute
  '/video/$n': typeof VideoNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/documents'
    | '/intro'
    | '/portal'
    | '/video/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/documents'
    | '/intro'
    | '/portal'
    | '/video/$n'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/documents'
    | '/intro'
    | '/portal'
    | '/video/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  IntroRoute: typeof IntroRoute
  PortalRoute: typeof PortalRoute
  VideoNRoute: typeof VideoNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$n': {
      id: '/video/$n'
      path: '/video/$n'
      fullPath: '/video/$n'
      preLoaderRoute: typeof VideoNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  IntroRoute: IntroRoute,
  PortalRoute: PortalRoute,
  VideoNRoute: VideoNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
